const { test, expect } = require('@playwright/test')

test.beforeEach(async ({ page }) => {
  // Team artwork is third-party and should never make UI behavior tests network-dependent.
  await page.route('https://a.espncdn.com/**', (route) => route.abort())
})

async function setPositionView(page, enabled = true) {
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Display/ }).click()
  const control = page.getByRole('checkbox', { name: 'By position' })
  if (enabled) await control.check()
  else await control.uncheck()
  await page.getByRole('button', { name: 'Close settings' }).click()
}

async function positionViewSetting(page) {
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Display/ }).click()
  return page.getByRole('checkbox', { name: 'By position' })
}

async function openCurrentSheet(page) {
  await page.getByRole('button', { name: /^Current sheet/ }).click()
}

async function openSnapshots(page) {
  await page.getByRole('button', { name: /^Snapshots/ }).click()
}

test('dashboard renders and exposes settings downloads', async ({ page }) => {
  await page.goto('./')
  await expect(page.getByRole('heading', { name: 'RankingsDiff' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Settings/ })).toBeVisible()
  await expect(page.locator('.team-badge').first()).toBeVisible()
  await expect(page.locator('.hero__context')).toContainText('Draft board')
  await expect(page.getByText('Full PPR', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Snapshots/ }).click()
  await expect(page.getByRole('link', { name: 'CSV' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'XLSX' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save draft' })).toBeVisible()
  await page.getByRole('button', { name: /^Ranking checks/ }).click()
  await expect(page.getByRole('link', { name: 'Run refresh workflow' })).toBeVisible()
  await page.getByRole('button', { name: /^Current sheet/ }).click()
  await expect(page.getByLabel('Position colors')).toHaveCount(0)
  const sourceLinkRadius = await page.getByRole('link', { name: /ESPN 2026 PPR300 PDF/ }).evaluate((link) => getComputedStyle(link).borderRadius)
  expect(parseFloat(sourceLinkRadius)).toBeLessThanOrEqual(10)
})

test('rankings diff opens as a separate route and returns without disturbing draft state', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Mark drafted Jahmyr Gibbs' }).first().click()
  await page.getByRole('button', { name: 'WR', exact: true }).first().click()
  await page.getByRole('button', { name: 'Rankings diff', exact: true }).click()

  await expect(page).toHaveURL(/\/analytics\/rankings-diff$/)
  await expect(page.getByRole('heading', { name: 'Rankings diff' })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Chart window' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Chart window' }).selectOption('50-150')
  await expect(page.locator('.rankings-diff-card__header')).toContainText('Picks 50–150')
  await expect(page.locator('.rankings-diff-point').first()).toBeVisible()
  await page.getByRole('combobox', { name: 'Chart window' }).selectOption('custom')
  await expect(page.getByRole('spinbutton', { name: 'Start pick' })).toBeVisible()
  await page.getByRole('spinbutton', { name: 'Start pick' }).fill('80')
  await page.getByRole('spinbutton', { name: 'End pick' }).fill('180')
  await expect(page.locator('.rankings-diff-card__header')).toContainText('Picks 80–180')

  await page.getByRole('button', { name: '← Back to rankings' }).click()
  await expect(page).toHaveURL(/\/RankingsDiff\/$|\/$/)
  await expect(page.getByRole('button', { name: 'WR', exact: true }).first()).toHaveClass(/active/)
  await page.getByRole('button', { name: 'ALL', exact: true }).first().click()
  await expect(page.getByRole('button', { name: "Undo drafted Jahmyr Gibbs" }).first()).toBeVisible()
})

test('rankings diff direct URL loads as a first-class view', async ({ page }) => {
  await page.goto('./analytics/rankings-diff')
  await expect(page.getByRole('heading', { name: 'Rankings diff' })).toBeVisible()
  await expect(page.getByRole('button', { name: '← Back to rankings' })).toBeVisible()
})

test('header mockup lab offers five compact directions', async ({ page }) => {
  await page.goto('./mockups')
  await expect(page.getByRole('heading', { name: 'Choose a calmer, more connected header.' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Header options' }).getByRole('button')).toHaveCount(5)
  await page.getByRole('button', { name: 'Close settings' }).click()
  await page.getByRole('button', { name: /Field Notes/ }).click()
  await expect(page.locator('.mock-dashboard__header--field')).toBeVisible()
  await expect(page.locator('body')).toHaveCSS('overflow-x', 'visible')
})

test('season and source switching works with manifest data', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Current sheet/ }).click()
  await page.locator('.settings-popover').getByLabel('Year').selectOption('2025')
  await page.locator('.settings-popover').getByLabel('Sheet').selectOption('espn')
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.locator('.price-heading').getByText('Value', { exact: true })).toBeVisible()
})

test('ESPN defaults to snake and exposes an auction format switch', async ({ page }) => {
  await page.goto('./')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await expect(page.locator('.view-summary')).toContainText('Snake')
  await page.getByRole('button', { name: /Settings/ }).click()
  await openCurrentSheet(page)
  const format = page.getByRole('group', { name: 'Draft format' })
  await expect(format.getByRole('button', { name: 'Snake', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await format.getByRole('button', { name: 'Auction', exact: true }).click()
  await expect(format.getByRole('button', { name: 'Auction', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.locator('.view-summary')).toContainText('Auction')
  await page.getByRole('button', { name: /Settings/ }).click()
  await openCurrentSheet(page)
  await page.getByRole('group', { name: 'Draft format' }).getByRole('button', { name: 'Snake', exact: true }).click()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.locator('.view-summary')).toContainText('Snake')
})

test('FantasyPros position view emphasizes source rank', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Current sheet/ }).click()
  await page.locator('.settings-popover').getByLabel('Sheet').selectOption('fpros')
  await page.getByRole('button', { name: 'Close settings' }).click()
  await setPositionView(page)
  await expect(page.locator('.position-lane--rb .position-player__metric strong').first()).toHaveText('#3')
  await expect(page.locator('.position-lane--rb .position-lane__columns')).toContainText('FP')
})

test('command-k focuses search and position filters rows', async ({ page }) => {
  await page.goto('./')
  await expect(page.getByPlaceholder(/Search by player or team/)).toBeVisible()
  await page.waitForTimeout(100)
  await page.evaluate(() => document.dispatchEvent(new KeyboardEvent('keydown', { key: 'k', metaKey: true, bubbles: true })))
  await expect(page.getByPlaceholder(/Search by player or team/)).toBeFocused()
  await page.getByPlaceholder(/Search by player or team/).fill('Ja')
  await expect(page.getByText("Ja'Marr Chase").first()).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByPlaceholder(/Search by player or team/)).not.toBeFocused()
  await page.keyboard.press('KeyW')
  await expect(page.getByRole('button', { name: 'WR' })).toHaveClass(/active/)
  await expect(page.getByRole('button', { name: /Settings/ })).toBeVisible()

  await page.keyboard.press(',')
  await expect(page.getByRole('dialog', { name: 'Settings' })).toBeVisible()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.getByText("Ja'Marr Chase").first()).toBeVisible()
  await page.getByPlaceholder(/Search by player or team/).fill('zzzz')
  await expect(page.getByText('No players match the current filters.')).toBeVisible()
})

test('slash focuses search and Enter drafts the first match', async ({ page }) => {
  await page.goto('./')
  const search = page.getByPlaceholder(/Search by player or team/)
  await page.getByRole('heading', { name: 'RankingsDiff' }).click()
  await page.keyboard.press('/')
  await expect(search).toBeFocused()
  await search.fill('Ja\'Marr')
  await page.keyboard.press('ArrowDown')
  await expect(page.locator('.rankings-table tbody tr.is-selected')).toContainText("Ja'Marr Chase")
  await page.keyboard.press('Enter')
  await expect(search).toHaveValue('')
  await expect(search).toBeFocused()
  await expect(page.getByRole('button', { name: "Undo drafted Ja'Marr Chase" }).first()).toBeVisible()

  await search.fill('Bijan')
  await page.getByRole('button', { name: 'Mark drafted Bijan Robinson' }).first().click()
  await expect(search).toHaveValue('')
  await expect(search).toBeFocused()
})

test('player search matches team city and nickname', async ({ page }) => {
  await page.goto('./')
  const search = page.getByPlaceholder('Search by player or team')
  await search.fill('Lions')
  await expect(page.getByText('Jahmyr Gibbs').first()).toBeVisible()
  await expect(page.getByText('Amon-Ra St. Brown').first()).toBeVisible()
  await search.fill('Detroit')
  await expect(page.getByText('Jahmyr Gibbs').first()).toBeVisible()
  await expect(page.getByText('Amon-Ra St. Brown').first()).toBeVisible()
})

test('command-z undoes and command-shift-z redoes draft and target actions', async ({ page }) => {
  await page.goto('./')
  const draft = page.getByRole('button', { name: "Mark drafted Ja'Marr Chase" }).first()
  await draft.click()
  await expect(page.getByRole('button', { name: "Undo drafted Ja'Marr Chase" }).first()).toBeVisible()
  await page.keyboard.press('Meta+z')
  await expect(page.getByRole('button', { name: "Mark drafted Ja'Marr Chase" }).first()).toBeVisible()
  await page.keyboard.press('Meta+Shift+z')
  await expect(page.getByRole('button', { name: "Undo drafted Ja'Marr Chase" }).first()).toBeVisible()

  const target = page.getByRole('button', { name: "Target Josh Allen" }).first()
  await target.click()
  await expect(page.getByRole('button', { name: "Remove target Josh Allen" }).first()).toBeVisible()
  await page.keyboard.press('Meta+z')
  await expect(page.getByRole('button', { name: "Target Josh Allen" }).first()).toBeVisible()
  await page.keyboard.press('Meta+Shift+z')
  await expect(page.getByRole('button', { name: "Remove target Josh Allen" }).first()).toBeVisible()
})

test('position filters show live drafted counts', async ({ page }) => {
  await page.goto('./')
  const count = (position) => page.getByRole('button', { name: position, exact: true }).locator('.position-pill__count')
  await expect(count('ALL')).toHaveText('0')
  await expect(count('RB')).toHaveText('0')
  await page.getByRole('button', { name: 'Mark drafted Jahmyr Gibbs' }).first().click()
  await expect(count('ALL')).toHaveText('1')
  await expect(count('RB')).toHaveText('1')
  await expect(count('WR')).toHaveText('0')
})

test('position view keyboard shortcuts toggle individual lanes', async ({ page }) => {
  await page.goto('./')
  await setPositionView(page)
  await page.getByRole('heading', { name: 'RankingsDiff' }).click()
  await expect(page.getByRole('heading', { name: 'Running backs' })).toBeVisible()
  await page.keyboard.press('r')
  await expect(page.getByRole('heading', { name: 'Running backs' })).toHaveCount(0)
  await page.keyboard.press('w')
  await expect(page.getByRole('heading', { name: 'Wide receivers' })).toHaveCount(0)
  await page.keyboard.press('r')
  await expect(page.getByRole('heading', { name: 'Running backs' })).toBeVisible()
})

test('P toggles the position view', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('heading', { name: 'RankingsDiff' }).click()
  await page.keyboard.press('p')
  let byPosition = await positionViewSetting(page)
  await expect(byPosition).toBeChecked()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await page.keyboard.press('p')
  byPosition = await positionViewSetting(page)
  await expect(byPosition).not.toBeChecked()
  await page.getByRole('button', { name: 'Close settings' }).click()
})

test('D toggles drafted players and Display is the default settings pane', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Mark drafted Jahmyr Gibbs' }).first().click()
  await expect(page.getByText('Jahmyr Gibbs').first()).toBeVisible()
  await page.getByRole('heading', { name: 'RankingsDiff' }).click()
  await page.keyboard.press('d')
  await expect(page.getByRole('button', { name: 'Mark drafted Jahmyr Gibbs' }).first()).toHaveCount(0)
  await page.keyboard.press('d')
  await expect(page.getByRole('button', { name: 'Undo drafted Jahmyr Gibbs' }).first()).toBeVisible()
  await page.getByRole('button', { name: /Settings/ }).click()
  await expect(page.getByRole('button', { name: /^Display/ })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByRole('checkbox', { name: 'Show drafted' })).toBeChecked()
})

test('recent picks stay horizontal, show the latest names, and omit draft labels and source rank', async ({ page }) => {
  await page.goto('./')
  for (let index = 0; index < 6; index += 1) {
    await page.locator('.rankings-table tbody tr').nth(index).locator('.draft-action').click()
  }
  const list = page.locator('.recent-draft__list')
  await expect(list).toBeVisible()
  await expect(list).not.toContainText('Last pick')
  await expect(list).not.toContainText('Drafted')
  await expect(list).not.toContainText('Pick 5')
  await expect(list).not.toContainText('source rank')
  await expect(list.locator('li')).toHaveCount(6)
  expect(await list.evaluate((node) => getComputedStyle(node).display)).toBe('flex')
})

test('recent picks can add a hidden drafted player to my roster', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Mark drafted Jahmyr Gibbs' }).first().click()
  await page.getByRole('button', { name: /Settings/ }).click()
  await expect(page.getByRole('button', { name: /^Display/ })).toHaveAttribute('aria-current', 'page')
  await page.getByRole('checkbox', { name: 'Show drafted' }).uncheck()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await page.getByRole('button', { name: 'Add Jahmyr Gibbs to my roster' }).first().click()
  await expect(page.getByLabel('My draft roster')).toContainText('Jahmyr Gibbs')
  await expect(page.getByRole('button', { name: 'Remove Jahmyr Gibbs from my roster' }).first()).toBeVisible()
})

test('roster players can be dragged between slots', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Mark drafted Jahmyr Gibbs' }).first().click()
  await page.getByLabel('Recent draft picks').getByRole('button', { name: 'Add Jahmyr Gibbs to my roster' }).click()
  const roster = page.getByLabel('My draft roster')
  await expect(roster.locator('[data-roster-slot="RB1"]')).toContainText('Jahmyr Gibbs')
  await roster.locator('[data-roster-slot="RB1"]').scrollIntoViewIfNeeded()
  await roster.locator('[data-roster-slot="RB2"]').scrollIntoViewIfNeeded()
  await roster.locator('[data-roster-slot="RB1"]').dragTo(roster.locator('[data-roster-slot="RB2"]'))
  await expect(roster.locator('[data-roster-slot="RB2"]')).toContainText('Jahmyr Gibbs')
  await expect(roster.locator('[data-roster-slot="RB1"]')).toContainText('Open')
})

test('mobile 390px uses cards and has no horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 900 })
  await page.goto('./')
  await expect(page.locator('.table-wrap')).toBeHidden()
  await expect(page.locator('.cards-list')).toBeVisible()
  await expect(page.getByLabel('Sort controls')).toBeVisible()
  await page.getByLabel('Sort by', { exact: true }).selectOption('player')
  await expect(page.locator('.cards-list .ranking-card').first()).toContainText('A.J. Brown')
  await page.getByRole('button', { name: 'Sort descending' }).click()
  await expect(page.locator('.cards-list .ranking-card').first()).toContainText('Zay Flowers')
  await expect(page.locator('.ranking-card').filter({ hasText: 'Jahmyr Gibbs' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Target Jahmyr Gibbs' }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Target Jahmyr Gibbs' }).last().click()
  await expect(page.getByLabel('Target queue', { exact: true }).last()).toContainText('$57 → $57')
  const queueBox = await page.getByLabel('Target queue', { exact: true }).evaluate((node) => {
    const rect = node.getBoundingClientRect()
    return { left: rect.left, right: rect.right, width: rect.width }
  })
  expect(queueBox.left).toBeLessThanOrEqual(14)
  expect(queueBox.right).toBeGreaterThanOrEqual(376)
  await expect(page.getByRole('combobox', { name: 'Position filter' })).toBeVisible()
  await expect(page.getByLabel('Sort controls')).toBeVisible()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
  expect(overflow).toBe(false)
  await setPositionView(page)
  await expect(page.locator('.position-board')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Settings' })).toBeVisible()
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Snapshots/ }).click()
  await expect(page.getByRole('button', { name: 'Save draft' })).toBeVisible()
  await page.getByRole('button', { name: /^Ranking checks/ }).click()
  await expect(page.getByRole('link', { name: 'Run refresh workflow' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
})


test('mobile FantasyPros cards stretch and actions can be hidden', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 900 })
  await page.goto('./')
  await page.getByRole('button', { name: /Settings/ }).click()
  await openCurrentSheet(page)
  await page.locator('.settings-popover').getByLabel('Sheet').selectOption('fpros')
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.locator('.cards-list')).toBeVisible()
  await expect(page.locator('.ranking-card').first()).toContainText('FPros rank')
  const cardBox = await page.locator('.ranking-card').first().evaluate((node) => {
    const rect = node.getBoundingClientRect()
    return { left: rect.left, right: rect.right, width: rect.width }
  })
  expect(cardBox.left).toBeLessThanOrEqual(1)
  expect(cardBox.right).toBeGreaterThanOrEqual(389)
  await page.getByRole('checkbox', { name: 'Show actions' }).uncheck()
  await expect(page.locator('.ranking-card__actions').first()).toBeHidden()
  await expect(page.getByRole('button', { name: /Mark drafted/ })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
})

test('mobile 320px has no horizontal overflow in board, settings, and source checks', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 900 })
  await page.goto('./')
  await expect(page.locator('.cards-list')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Ranking checks/ }).click()
  await expect(page.getByRole('heading', { name: 'Ranking change checks' })).toBeVisible()
  const sourceHeaderWidth = await page.locator('.source-checks__header').evaluate((node) => node.getBoundingClientRect().width)
  expect(sourceHeaderWidth).toBeLessThanOrEqual(288)
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
})

test('table headers stay compact across browser widths', async ({ page }) => {
  for (const width of [768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('./')
    await expect(page.locator('.rankings-table')).toBeVisible()
    await expect(page.locator('.rank-heading')).toContainText('Rank')
    await expect(page.locator('.rank-heading__sorts')).toContainText('SRC')
    await expect(page.locator('.rank-heading__sorts')).toContainText('Adj')
    await expect(page.locator('.price-heading').getByText('Value', { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Sort by value delta' })).toHaveText('Delta')
    await expect(page.locator('.price-heading .sort-button')).toHaveCount(0)
    const sortSizing = await page.locator('.search-sort-control').evaluate((node) => { const select = node.querySelector('select'); return { control: node.getBoundingClientRect().width, height: node.getBoundingClientRect().height, select: select?.getBoundingClientRect().width ?? 0, selectHeight: select?.getBoundingClientRect().height ?? 0 } })
    if (width >= 761) {
      expect(sortSizing.control).toBeLessThanOrEqual(320)
      expect(sortSizing.select).toBeLessThanOrEqual(180)
      expect(sortSizing.selectHeight).toBeLessThan(sortSizing.height)
      expect(sortSizing.selectHeight).toBeGreaterThanOrEqual(sortSizing.height * .75)
    }
    const layout = await page.evaluate(() => ({
      overflow: document.documentElement.scrollWidth > document.documentElement.clientWidth,
      headerRight: document.querySelector('.rankings-table thead')?.getBoundingClientRect().right ?? 0,
      viewportRight: window.innerWidth
    }))
    expect(layout.overflow).toBe(false)
    expect(layout.headerRight).toBeLessThanOrEqual(layout.viewportRight + 1)
  }
})

test('desktop table stays inside the board column beside the target queue', async ({ page }) => {
  await page.setViewportSize({ width: 2048, height: 900 })
  await page.goto('./')
  await expect(page.getByLabel('Target queue', { exact: true })).toBeVisible()
  const layout = await page.evaluate(() => {
    const table = document.querySelector('.table-wrap')?.getBoundingClientRect()
    const queue = document.querySelector('.target-queue')?.getBoundingClientRect()
    return { tableRight: table?.right ?? 0, queueLeft: queue?.left ?? 0, viewportRight: window.innerWidth, overflow: document.documentElement.scrollWidth > document.documentElement.clientWidth }
  })
  expect(layout.overflow).toBe(false)
  expect(layout.tableRight).toBeLessThanOrEqual(layout.queueLeft - 8)
  expect(layout.queueLeft).toBeLessThan(layout.viewportRight)
})

test('diff values use a flat treatment instead of looking like input boxes', async ({ page }) => {
  await page.goto('./')
  const diff = page.locator('.diff-value').first()
  await expect(diff).toBeVisible()
  const style = await diff.evaluate((node) => {
    const computed = getComputedStyle(node)
    return { border: computed.border, radius: computed.borderRadius, display: computed.display }
  })
  expect(style.border).toMatch(/0px/)
  expect(style.radius).toBe('0px')
  expect(style.display).toBe('inline-flex')
})


test('target queue is controlled from settings and works in both views', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: "Target Ja'Marr Chase" }).first().click()
  await expect(page.getByLabel('Target queue', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Target queue', { exact: true })).toContainText('Shortlist')
  await expect(page.getByLabel('Target queue', { exact: true })).toContainText('WR')

  await setPositionView(page)
  await expect(page.getByLabel('Target queue', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Display/ }).click()
  await page.getByRole('checkbox', { name: 'Show target queue' }).uncheck()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.getByLabel('Target queue', { exact: true })).toHaveCount(0)
  await expect(page.locator('.draft-board-layout')).toHaveClass(/draft-board-layout--queue-hidden/)

  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Display/ }).click()
  await page.getByRole('checkbox', { name: 'Show target queue' }).check()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.getByLabel('Target queue', { exact: true })).toBeVisible()

  await page.setViewportSize({ width: 390, height: 900 })
  await expect(page.getByLabel('Target queue', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
})

test('display settings can hide and restore the recent draft log', async ({ page }) => {
  await page.goto('./')
  await expect(page.getByLabel('Recent draft picks')).toHaveCount(0)
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Display/ }).click()
  await page.getByRole('checkbox', { name: 'Keep controls up top' }).check()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.locator('.dashboard-workbench--sticky')).toBeVisible()

  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Display/ }).click()
  await page.getByRole('checkbox', { name: 'Show draft log' }).uncheck()
  await page.getByRole('checkbox', { name: 'Keep controls up top' }).uncheck()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.getByLabel('Recent draft picks')).toHaveCount(0)

  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Display/ }).click()
  await page.getByRole('checkbox', { name: 'Show draft log' }).check()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.getByLabel('Recent draft picks')).toHaveCount(0)
})

test('roster target settings update expected spend by slot', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: /Settings/ }).click()
  await openCurrentSheet(page)
  await page.getByRole('group', { name: 'Draft format' }).getByRole('button', { name: 'Auction', exact: true }).click()
  await page.getByRole('button', { name: /^Roster targets/ }).click()
  await page.getByLabel('Expected price for RB1').fill('60')
  await page.getByLabel('Close settings').click()
  await expect(page.getByLabel('My draft roster')).toContainText('target $60')
})

test('auction target status uses subtle under and over treatments', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: /Settings/ }).click()
  await openCurrentSheet(page)
  await page.getByRole('group', { name: 'Draft format' }).getByRole('button', { name: 'Auction', exact: true }).click()
  await page.getByRole('button', { name: 'Close settings' }).click()

  const row = page.locator('.rankings-table--espn tbody tr').first()
  const player = await row.locator('.player-cell strong').textContent()
  if (!player) throw new Error('Expected a player name')
  await row.getByRole('button', { name: `Mark drafted ${player}` }).click()
  await page.getByRole('button', { name: `Add ${player} to my roster` }).first().click()
  const roster = page.getByLabel('My draft roster')
  const price = roster.getByRole('button', { name: `Set price paid for ${player}` })
  await price.click()
  await roster.getByRole('textbox', { name: `Price paid for ${player}` }).fill('1')
  await roster.getByRole('textbox', { name: `Price paid for ${player}` }).press('Enter')
  await expect(roster.locator('.auction-roster-panel__target-status')).toHaveClass(/is-under/)
  await roster.getByRole('button', { name: `Edit price paid for ${player}` }).click()
  await roster.getByRole('textbox', { name: `Price paid for ${player}` }).fill('200')
  await roster.getByRole('textbox', { name: `Price paid for ${player}` }).press('Enter')
  await expect(roster.locator('.auction-roster-panel__target-status')).toHaveClass(/is-over/)
})

test('targets and drafted state persist per sheet', async ({ page }) => {
  await page.goto('./')
  const target = page.getByRole('button', { name: "Target Ja'Marr Chase" }).first()
  await target.click()
  await expect(page.getByRole('button', { name: "Remove target Ja'Marr Chase" }).first()).toBeVisible()
  await page.getByRole('button', { name: "Mark drafted Ja'Marr Chase" }).first().click()
  await expect(page.getByRole('button', { name: "Undo drafted Ja'Marr Chase" }).first()).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: "Undo drafted Ja'Marr Chase" }).first()).toBeVisible()
})


test('click selection supports arrows and enter drafting in board and position views', async ({ page }) => {
  await page.goto('./')
  const firstBoardRow = page.locator('.rankings-table tbody tr').first()
  await firstBoardRow.click()
  await expect(firstBoardRow).toHaveClass(/is-selected/)
  await page.keyboard.press('f')
  await expect(page.getByRole('button', { name: 'Remove target Jahmyr Gibbs' }).first()).toBeVisible()
  await expect(page.getByLabel('Target queue', { exact: true })).toContainText('Jahmyr Gibbs')
  await page.keyboard.press('f')
  await expect(page.getByRole('button', { name: 'Target Jahmyr Gibbs' }).first()).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(firstBoardRow).not.toHaveClass(/is-selected/)
  await firstBoardRow.click()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Undo drafted Jahmyr Gibbs' }).first()).toBeVisible()
  const secondBoardRow = page.locator('.rankings-table tbody tr').nth(1)
  await expect(secondBoardRow).toHaveClass(/is-selected/)
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Undo drafted Bijan Robinson' }).first()).toBeVisible()

  const thirdBoardRow = page.locator('.rankings-table tbody tr').nth(2)
  await expect(thirdBoardRow).toHaveClass(/is-selected/)

  await setPositionView(page)
  const firstRunningBack = page.locator('.position-lane--rb .position-player').first()
  await firstRunningBack.click()
  await expect(firstRunningBack).toHaveClass(/is-selected/)
  await page.keyboard.press('f')
  await expect(page.getByRole('button', { name: 'Remove Jahmyr Gibbs from my roster' }).first()).toBeVisible()
  await page.keyboard.press('ArrowRight')
  const firstWideReceiver = page.locator('.position-lane--wr .position-player').first()
  await expect(firstWideReceiver).toHaveClass(/is-selected/)
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Undo drafted Puka Nacua' }).first()).toBeVisible()
  await expect(page.locator('.position-lane--wr .position-player').nth(1)).toHaveClass(/is-selected/)

  await page.keyboard.press('ArrowLeft')
  await expect(page.locator('.position-lane--rb .position-player').nth(1)).toHaveClass(/is-selected/)
  await page.keyboard.press('Escape')
  await expect(page.locator('.position-player.is-selected')).toHaveCount(0)
})

test('position overview shows all lanes without collisions', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('./')
  await setPositionView(page)
  for (const heading of ['Running backs', 'Wide receivers', 'Quarterbacks', 'Tight ends']) {
    await expect(page.getByRole('heading', { name: heading })).toBeVisible()
  }
  await expect(page.locator('.position-player .team-badge').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
  expect(await page.locator('.position-board').evaluate((board) => getComputedStyle(board).gridTemplateColumns.split(' ').length)).toBe(2)
  const overlaps = await page.locator('.position-player').evaluateAll((rows) => rows.some((row) => {
    const cells = [...row.children].filter((cell) => getComputedStyle(cell).display !== 'none').map((cell) => cell.getBoundingClientRect())
    return cells.some((cell, index) => index > 0 && cell.left < cells[index - 1].right - 1)
  }))
  expect(overlaps).toBe(false)
  const firstMetric = page.locator('.position-lane--rb .position-player__metric strong').first()
  await expect(firstMetric).toHaveText('$57')
  await expect(page.locator('.position-lane--rb .position-lane__columns')).toContainText('ESPN')
  await expect(page.locator('.position-lane--rb .position-player__difference').first()).toHaveText('$0')
  expect(await page.locator('.position-lane--rb .position-player').first().evaluate((row) => row.style.getPropertyValue('--diff-alpha'))).toBe('')
  expect(await page.locator('.position-lane--wr .position-player').filter({ hasText: 'Drake London' }).evaluate((row) => Number(row.style.getPropertyValue('--diff-alpha')))).toBeGreaterThan(0)
  const runningBacks = page.getByLabel('RB players, scroll to see all')
  await expect(runningBacks.locator('.position-player')).not.toHaveCount(6)
  expect(await runningBacks.locator('.position-player').count()).toBeGreaterThan(6)
  const scrollMetrics = await runningBacks.evaluate((list) => ({ clientHeight: list.clientHeight, scrollHeight: list.scrollHeight, overflowY: getComputedStyle(list).overflowY }))
  expect(scrollMetrics.overflowY).toBe('auto')
  expect(scrollMetrics.scrollHeight).toBeGreaterThan(scrollMetrics.clientHeight)
  await runningBacks.focus()
  await runningBacks.evaluate((list) => { list.scrollTop = list.scrollHeight })
  await expect(runningBacks.locator('.position-player').last()).toBeVisible()

  await page.getByRole('button', { name: 'QB' }).click()
  expect(await page.locator('.position-board').getAttribute('data-count')).toBe('3')
  expect(await page.locator('.position-board').evaluate((board) => getComputedStyle(board).gridTemplateColumns.split(' ').length)).toBe(3)
  await page.getByRole('button', { name: 'TE', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Quarterbacks' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Tight ends' })).toHaveCount(0)
  await expect(page.locator('.position-board')).toHaveAttribute('data-count', '2')
})

test('team logos are centered inside badges', async ({ page }) => {
  await page.goto('./')
  expect(await page.locator('.player-cell__inner').first().evaluate((cell) => parseFloat(getComputedStyle(cell).columnGap))).toBeGreaterThanOrEqual(10)
  const offset = await page.locator('.team-badge:has(img)').first().evaluate((badge) => {
    const image = badge.querySelector('img')
    const badgeBox = badge.getBoundingClientRect()
    const imageBox = image.getBoundingClientRect()
    return {
      x: Math.abs((badgeBox.left + badgeBox.width / 2) - (imageBox.left + imageBox.width / 2)),
      y: Math.abs((badgeBox.top + badgeBox.height / 2) - (imageBox.top + imageBox.height / 2))
    }
  })
  expect(offset.x).toBeLessThanOrEqual(1)
  expect(offset.y).toBeLessThanOrEqual(1)
})

test('double-clicking a position isolates that lane', async ({ page }) => {
  await page.goto('./')
  await setPositionView(page)
  await page.getByRole('button', { name: 'WR', exact: true }).dblclick()
  await expect(page.getByRole('heading', { name: 'Wide receivers' })).toBeVisible()
  await expect(page.locator('.position-board')).toHaveAttribute('data-count', '1')
  await expect(page.getByRole('heading', { name: 'Running backs' })).toHaveCount(0)
})

test('draft board position filters can combine positions', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'QB', exact: true }).click()
  await page.getByRole('button', { name: 'WR', exact: true }).click()
  await expect(page.getByRole('button', { name: 'QB', exact: true })).toHaveClass(/active/)
  await expect(page.getByRole('button', { name: 'WR', exact: true })).toHaveClass(/active/)
  await expect(page.getByRole('button', { name: 'RB', exact: true })).not.toHaveClass(/active/)
  await expect(page.getByRole('button', { name: 'ALL', exact: true })).not.toHaveClass(/active/)
})

test('table headings stick while draft rows scroll', async ({ page }) => {
  await page.goto('./')
  await expect(page.locator('.rankings-table th').first()).toHaveCSS('position', 'static')
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Display/ }).click()
  await page.getByLabel('Keep controls up top').check()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.locator('.dashboard-workbench')).toHaveCSS('position', 'sticky')
  await expect(page.locator('.rankings-table').first()).toHaveClass(/sticky-headers/)
  await expect(page.locator('.rankings-table th').first()).toHaveCSS('position', 'sticky')
  await page.locator('.rankings-table tbody tr').nth(30).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => window.scrollY)).toBeGreaterThan(0)
  const top = await page.locator('.rankings-table th').first().evaluate((heading) => heading.getBoundingClientRect().top)
  const workbenchBottom = await page.locator('.dashboard-workbench').evaluate((workbench) => workbench.getBoundingClientRect().bottom)
  expect(top).toBeGreaterThanOrEqual(workbenchBottom - 1)
  expect(top).toBeLessThanOrEqual(workbenchBottom + 1)
})

test('sticky workbench keeps search, recent picks, headers, and roster visible', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Display/ }).click()
  await page.getByLabel('Keep controls up top').check()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.locator('.dashboard-workbench')).toHaveCSS('position', 'sticky')
  await expect(page.locator('.dashboard-workbench [data-player-search]')).toBeVisible()
  await expect(page.getByLabel('My draft roster')).toBeVisible()
  await page.locator('.rankings-table tbody tr').nth(30).scrollIntoViewIfNeeded()
  await expect(page.locator('.dashboard-workbench')).toBeVisible()
  await expect(page.locator('.rankings-table th').first()).toBeVisible()
  await expect(page.getByLabel('My draft roster')).toBeVisible()
})

test('draft JSON can be saved, cleared, and restored by player key', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: "Target Ja'Marr Chase" }).first().click()
  await page.getByRole('button', { name: "Mark drafted Ja'Marr Chase" }).first().click()
  await page.getByLabel('Recent draft picks').getByRole('button', { name: "Add Ja'Marr Chase to my roster" }).click()

  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Snapshots/ }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Save draft' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('rankingsdiff-2026-espn-draft.json')
  const stream = await download.createReadStream()
  let contents = ''
  for await (const chunk of stream) contents += chunk.toString()
  const saved = JSON.parse(contents)
  expect(saved.version).toBe(2)
  expect(saved.players.drafted).toContain("ja'marr chase|cin")
  expect(saved.roster.mine).toContain("ja'marr chase|cin")
  expect(saved).not.toHaveProperty('rows')

  await page.getByRole('button', { name: 'Clear draft' }).click()
  await expect(page.getByRole('heading', { name: 'Clear this draft?' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear without saving' }).click()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.getByRole('button', { name: "Mark drafted Ja'Marr Chase" }).first()).toBeVisible()

  await page.getByRole('button', { name: /Settings/ }).click()
  await openSnapshots(page)
  await page.getByLabel('Upload draft JSON').setInputFiles({
    name: 'saved-draft.json',
    mimeType: 'application/json',
    buffer: Buffer.from(contents)
  })
  await expect(page.getByRole('button', { name: "Undo drafted Ja'Marr Chase" }).first()).toBeVisible()
  await expect(page.getByLabel('My draft roster')).toContainText("Ja'Marr Chase")
  await expect(page.getByText('Draft restored.')).toBeVisible()
})

test('recent picks show newest first with team logos and expanded names', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: "Mark drafted Jahmyr Gibbs" }).first().click()
  await page.getByRole('button', { name: "Mark drafted Bijan Robinson" }).first().click()
  const log = page.getByLabel('Recent draft picks')
  await expect(log.locator('li').first()).toContainText('Bijan Robinson')
  await expect(log.locator('li').nth(1)).toContainText('Jahmyr Gibbs')
  await expect(log.locator('li').first().locator('.team-badge')).toBeVisible()
  await expect(log.locator('li').first()).not.toContainText('$55')
})

test('draft view and filters survive refresh', async ({ page }) => {
  await page.goto('./')
  await setPositionView(page)
  await page.getByRole('button', { name: 'WR', exact: true }).dblclick()
  await page.getByPlaceholder('Search by player or team').fill('London')
  await page.reload()
  const byPosition = await positionViewSetting(page)
  await expect(byPosition).toBeChecked()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.getByRole('button', { name: 'WR', exact: true })).toHaveClass(/active/)
  await expect(page.getByPlaceholder('Search by player or team')).toHaveValue('London')
  await expect(page.getByRole('heading', { name: 'Wide receivers' })).toBeVisible()
})

test('spacing options preview renders layout ideas', async ({ page }) => {
  await page.goto('./spacing-options.html')
  await expect(page.getByRole('heading', { name: 'Full-name layouts for rankings' })).toBeVisible()
  await expect(page.locator('.option')).toHaveCount(6)
  await expect(page.getByText('Option B: Stacked price + soft edge')).toBeVisible()
  await expect(page.getByText('Option D: Value cards with labeled pills')).toBeVisible()
  await expect(page.getByText('Kenneth Walker III').first()).toBeVisible()
  await expect(page.getByText('Amon-Ra St. Brown').first()).toBeVisible()
  expect(await page.locator('.name strong, .gradient-card h4, .mobile-card h4, .mobile-row strong, .lane-row strong').allTextContents()).not.toContain('…')
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
})

test('split browser width keeps the condensed rankings board layout', async ({ page }) => {
  await page.setViewportSize({ width: 640, height: 900 })
  await page.goto('./')
  await expect(page.locator('.table-wrap')).toBeVisible()
  await expect(page.locator('.cards-list')).toBeHidden()
  await expect(page.getByLabel('Recent draft picks')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
})

test('workbench stays cohesive across five browser sizes', async ({ page }) => {
  for (const size of [{ width: 1440, height: 1000 }, { width: 1100, height: 900 }, { width: 768, height: 900 }, { width: 390, height: 900 }, { width: 320, height: 800 }]) {
    await page.setViewportSize(size)
    await page.goto('./')
    await expect(page.getByPlaceholder('Search by player or team')).toBeVisible()
    await expect(page.getByRole('button', { name: /Settings/ })).toBeVisible()
    await expect(page.getByText('Shortlist', { exact: true }).last()).toBeVisible()
    const layout = await page.evaluate(() => ({ overflow: document.documentElement.scrollWidth > document.documentElement.clientWidth, workbench: getComputedStyle(document.querySelector('.dashboard-workbench')).display }))
    expect(layout.overflow).toBe(false)
    if (size.width >= 1101) expect(layout.workbench).toBe('grid')
  }
})

test('adjusted rankings switch between full PPR Winks and half PPR Winks', async ({ page }) => {
  await page.goto('./')
  await page.getByPlaceholder('Search by player or team').fill('Amon-Ra')
  const fullPprRank = await page.locator('table tbody tr').first().locator('.rank-pair strong').nth(1).textContent()
  expect(fullPprRank).toBeTruthy()
  await page.getByRole('button', { name: /Settings/ }).click()
  await openCurrentSheet(page)
  await expect(page.getByLabel('Adjusted rankings')).toHaveValue('full-ppr')
  await expect(page.getByText(/Source updated/)).toBeVisible()
  await page.getByLabel('Adjusted rankings').selectOption('half-ppr')
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.locator('table tbody tr').first().locator('.rank-pair strong').nth(1)).not.toHaveText(fullPprRank ?? '')
})

test('settings shows only the active source pages', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: /Settings/ }).click()
  await openCurrentSheet(page)
  const links = page.getByLabel('Ranking source pages').locator('a')
  await expect(links).toHaveCount(2)
  await expect(links).toContainText(['ESPN 2026 PPR300 PDF', 'Yahoo · Consensus Full-PPR rankings'])
  await page.getByLabel('Adjusted rankings').selectOption('half-ppr')
  await expect(links).toContainText(['ESPN 2026 PPR300 PDF', 'Yahoo · Hayden Winks Half-PPR rankings'])
})

test('snake roster hides auction target amounts', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: /Settings/ }).click()
  await openCurrentSheet(page)
  await page.getByLabel('Sheet').selectOption('fpros')
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.locator('.view-summary')).toContainText('Snake')
  await expect(page.getByLabel('My draft roster')).not.toContainText(/Under target|Over target|target \$/)
})

test('snake roster assigns the first available draft round', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: /Settings/ }).click()
  await openCurrentSheet(page)
  await page.getByLabel('Sheet').selectOption('fpros')
  await page.getByRole('button', { name: 'Close settings' }).click()

  const rows = page.locator('.rankings-table--fpros tbody tr')
  const roster = page.getByLabel('My draft roster')
  for (let index = 0; index < 4; index += 1) {
    const player = await rows.nth(index).locator('.player-cell strong').textContent()
    if (!player) throw new Error('Expected a player name')
    await rows.nth(index).getByRole('button', { name: `Mark drafted ${player}` }).click()
    await page.getByRole('button', { name: `Add ${player} to my roster` }).first().click()
    await expect(roster.getByRole('button', { name: `Edit draft round for ${player}` })).toContainText(`R${index + 1}`)
  }
})

test('snake recent picks show editable overall picks and support reordering', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: /Settings/ }).click()
  await openCurrentSheet(page)
  await page.getByLabel('Sheet').selectOption('fpros')
  await page.getByRole('button', { name: 'Close settings' }).click()
  const rows = page.locator('.rankings-table--fpros tbody tr')
  for (let index = 0; index < 3; index += 1) await rows.nth(index).locator('.draft-action').click()
  const list = page.getByLabel('Recent draft picks').locator('.recent-draft__list')
  const latest = list.locator('li').first()
  const latestName = await latest.locator('.recent-draft__identity strong').textContent()
  if (!latestName) throw new Error('Expected latest drafted player')
  const pickInput = latest.getByRole('spinbutton', { name: `Overall pick for ${latestName}` })
  await expect(pickInput).toHaveValue('3')
  await pickInput.fill('24')
  await expect(pickInput).toHaveValue('24')
  await list.locator('li').nth(2).dragTo(list.locator('li').first())
  await expect(list.locator('li')).toHaveCount(3)
})

test('Yahoo projection column is hidden by default and can be toggled', async ({ page }) => {
  await page.goto('./')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await expect(page.locator('.rankings-table')).toBeVisible()
  await expect(page.locator('.yahoo-projection-heading')).toHaveCount(0)
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Display/ }).click()
  const yahooToggle = page.getByRole('checkbox', { name: 'Show Yahoo projections' })
  await expect(yahooToggle).not.toBeChecked()
  await yahooToggle.check()
  await expect(yahooToggle).toBeChecked()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.locator('.yahoo-projection-heading')).toHaveCount(1)
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Display/ }).click()
  await page.getByRole('checkbox', { name: 'Show Yahoo projections' }).uncheck()
  await yahooToggle.uncheck()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.locator('.yahoo-projection-heading')).toHaveCount(0)
})

test('Yahoo projections render the selected scoring format and are searchable', async ({ page }) => {
  await page.route('**/data/manifest.json', async (route) => {
    const response = await route.fetch()
    const manifest = await response.json()
    manifest.seasons[0].yahooProjections = '/data/test-yahoo-projections.json'
    await route.fulfill({ response, json: manifest })
  })
  await page.route('**/data/test-yahoo-projections.json', async (route) => {
    await route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify([{ player: 'Bijan Robinson', team: 'ATL', week1Ppr: 20.5, week1HalfPpr: 18.5, weeklyAvgPpr: 14.2, weeklyAvgHalfPpr: 12.1 }])
    })
  })
  await page.goto('./')
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Display/ }).click()
  await page.getByRole('checkbox', { name: 'Show Yahoo projections' }).check()
  await page.getByRole('button', { name: 'Close settings' }).click()
  const row = page.locator('tbody tr').filter({ hasText: 'Bijan Robinson' }).first()
  await expect(row.locator('.yahoo-projection-cell')).toContainText('20.50')
  await expect(row.locator('.yahoo-projection-cell')).toContainText('14.2 avg')
  await page.getByRole('button', { name: /Settings/ }).click()
  await page.getByRole('button', { name: /^Current sheet/ }).click()
  await page.getByText('Adjusted rankings').locator('..').getByRole('combobox').selectOption('half-ppr')
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(row.locator('.yahoo-projection-cell')).toContainText('18.50')
  await expect(row.locator('.yahoo-projection-cell')).toContainText('12.1 avg')
  await page.getByPlaceholder('Search by player or team').fill('Bijan')
  await expect(page.locator('tbody tr')).toHaveCount(1)
})
